services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  server:
    build: ./server
    container_name: server
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    depends_on:
      - db

  client:
    build:
      context: ./client
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    container_name: client
    ports:
        - "${CLIENT_PORT}:80"
    env_file:
        - .env
    depends_on:
        - server
    stdin_open: true
    tty: true

volumes:
    mysql_data:
