services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    #command: --default-authentication-plugin=mysql_native_password

  server:
    build: 
      context: ./server
      target: dev
    container_name: server
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./server:/app             # mount code từ host → container
      - /app/node_modules         # giữ lại node_modules của container
    command: >
      /wait-for.sh db 3306
      sh -c "npx sequelize-cli db:migrate && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true # fix hot reload cho nodemon trong Docker

  client:
    build:
      context: ./client
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    container_name: client
    ports:
        - "${CLIENT_PORT}:80"
    env_file:
        - .env
    depends_on:
        - server
    stdin_open: true
    tty: true

volumes:
    mysql_data:
