const actionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL:'REGISTER_FAIL',
    RESET_REGISTER_STATUS : "RESET_REGISTER_STATUS",
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_CURRENT: 'GET_CURRENT',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',

    GET_MOVIES: 'GET_MOVIES',
    GET_MOVIE_DETAIL: 'GET_MOVIE_DETAIL',

    GET_ALL_CINEMA_CHAINS: 'GET_ALL_CINEMA_CHAINS',
    GET_CINEMA_CHAIN_DETAIL: 'GET_CINEMA_CHAIN_DETAIL',
    GET_CINEMA_CLUSTER_DETAIL: 'GET_CINEMA_CLUSTER_DETAIL',
    GET_CINEMA_DETAIL: 'GET_CINEMA_DETAIL',
    GET_CINEMA_CLUSTER: 'GET_CINEMA_CLUSTER',
    GET_ALL_CINEMA_CLUSTERS: 'GET_ALL_CINEMA_CLUSTERS',
    GET_ALL_CINEMAS: 'GET_ALL_CINEMAS',
    GET_SHOWTIME: 'GET_SHOWTIME',
    RESET_SHOWTIMES: 'RESET_SHOWTIMES',
    GET_SHOWTIME_DETAIL: 'GET_SHOWTIME_DETAIL',

    GET_SEATS: 'GET_SEATS',

    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAIL: 'CREATE_ORDER_FAIL',
    GET_ORDER_HISTORY_SUCCESS: 'GET_ORDER_HISTORY_SUCCESS',
    GET_ORDER_HISTORY_FAIL: 'GET_ORDER_HISTORY_FAIL',
    GET_ALL_USERS: 'GET_ALL_USERS',
    ADMIN_UPDATE_USER: 'ADMIN_UPDATE_USER'
}

export default actionTypes;